# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-23 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misago_threads', '0009_auto_20180326_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misago_threads.Thread'),
        ),
    ]
